baseURL = "https://carlynscookbook.netlify.com/"
languageCode = "en-us"
title = "Carlyn's Big Wrinkly Recipe Book"
theme = "recipes"

[params]
  author = "Jason Rametta"
  description = "Jason's Recipe Book"
